version: '3'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:15
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "pedidos"
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432"
    volumes:
      -  ./postgres-data:/var/lib/postgresql/data
    networks:
      - docker-network
    restart: always

  pedidos-api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: pedidos-api
    image: wesleyeduardodev/pedidos-api:latest
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: test
      TZ: "America/Sao_Paulo"
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    networks:
      - docker-network
    restart: always

networks:
  docker-network:
    driver: bridge